import Head from "next/head";
import Layout from "@/components/utils/Layout";
import Thumbnail from "@/components/utils/Thumbnail";
import Header from "@/components/home/Header";

export default function HomePage() {
  const main = `flex items-center text-dark w-full min-h-screen`;
  const layout = `pt-0`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={main}>
        <Layout className={layout}>
          <Header />
        </Layout>
        <Thumbnail />
      </main>
    </>
  );
}
