import Image from "next/image";
import Head from "next/head";
import Layout from "../components/utils/Layout";
import AnimatedText from "@/components/utils/AnimatedText";
import ProfileImage from "../../public/images/mobile-dev-1-vector.png";

export default function Home() {
  const mainStyles = `flex items-center text-dark w-full min-h-screen`;
  const layoutStyles = `pt-0`;
  const headerStyles = `flex items-center justify-between w-full`;
  const imgWrapperStyles = `w-1/2`;
  const imgStyles = `w-full h-auto`;
  const headingWrapperStyles = `w-1/2`;
  const nameStyles = `inline-block w-full text-dark font-bold capitalize text-8xl`;
  const titleStyles = `inline-block w-full text-dark font-bold capitalize text-6xl`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={mainStyles}>
        <Layout className={layoutStyles}>
          <div className={headerStyles}>
            <div className={imgWrapperStyles}>
              <Image
                src={ProfileImage}
                alt="Chris Kakos"
                className={imgStyles}
              />
            </div>
            <div className={headingWrapperStyles}>
              <AnimatedText text={"Chris Kakos"} className={nameStyles} />
              <AnimatedText
                text={"Full Stack Engineer"}
                className={titleStyles}
              />
              <p>
                blah blah blah blah blah blah blah blah blah blah blah blah blah
                blah blah blah blah blah blah blah blah blah blah blah blah blah
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
// className = { imgStyles };
