import Image from "next/image";
import Head from "next/head";
import Layout from "../components/utils/Layout";
import AnimatedText from "@/components/utils/AnimatedText";
import CustomLink from "@/components/utils/CustomLink";
import ProfileImage from "../../public/images/mobile-dev-1-vector.png";

export default function Home() {
  // Layout
  const main = `flex items-center text-dark w-full min-h-screen`;
  const layout = `pt-0`;
  // Header
  const header = `flex items-center justify-between w-[100%] border-2 border-blue-300`;
  const imgWrapper = `w-1/2 flex flex-col items-center self-center`;
  const img = `w-full h-auto`;
  const headingWrapper = `w-1/2`;
  const headingName = `inline-block w-full text-dark font-medium capitalize text-left text-7xl`;
  const headingTitle = `inline-block w-full text-dark font-extralight capitalize text-left text-5xl`;
  const headingSubtext = `my-4 text-base font-medium`;
  const buttonWrapper = ``;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={main}>
        <Layout className={layout}>
          {/* Header */}
          <div className={header}>
            {/* Header Image */}
            <div className={imgWrapper}>
              <Image src={ProfileImage} alt="Chris Kakos" className={img} />
            </div>
            {/* Header Heading */}
            <div className={headingWrapper}>
              <AnimatedText className={headingName} text={"Chris Kakos"} />
              <AnimatedText
                className={headingTitle}
                text={"Full Stack Engineer"}
              />
              <p className={headingSubtext}>
                blah blah blah blah blah blah blah blah blah blah blah blah blah
                blah blah blah blah blah blah blah blah blah blah blah blah blah
              </p>
              <div className={`${buttonWrapper}`}>
                <CustomLink
                  href={`/chris-kakos-resume-2023.pdf`}
                  title={"Resume"}
                  target={true}
                />
                <CustomLink
                  href={`mailto:ch2isk4kos@gmail.com`}
                  title={"Contact"}
                  target={true}
                />
                <CustomLink href={`https://react.dev`} title={"React"} />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
// className = { imgStyles };
